// GENERATED by scripts/fid-snapshot.mts — DO NOT EDIT. A hand edit is a suppression-class
// violation (Constitution XII); regenerate from a LOCAL api instead.
// Taken 2026-09-23 from a LOCAL nutrimero-api at 4a4356b332995fdcd326735f44de1cfd166f0c9c (contract/SOURCE),
// seeded with fid:import — NOT from api main, which has moved on (#80–#82: the declaration
// reference, refuse-on-gap issuing, the peanut/sulphite allergen guard); none of it changes these
// FID reads. Never taken from production.
import type { FidSnapshot } from "./fid-snapshot-types";

export const FID_SNAPSHOT = {
  apiCommit: "4a4356b332995fdcd326735f44de1cfd166f0c9c",
  contractSource: "nutrimero-api 4a4356b332995fdcd326735f44de1cfd166f0c9c (origin/main)",
  staples: [
    {
      fidId: "389D858",
      names: {
        en: ["wheat flour"],
        de: ["Weizenmehl"],
        hu: ["búzaliszt"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "no",
      },
      allergens: {
        CCG: "yes",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "4BEC221",
      names: {
        en: ["sugar"],
        de: ["Haushaltszucker", "Kristallzucker", "Saccharose", "Weißzucker", "Zucker"],
        hu: ["cukor"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "61CAB80",
      names: {
        en: ["butter"],
        de: ["Butter"],
        hu: ["vaj"],
      },
      dietary: {
        vegan: "no",
        vegetarian: "yes",
        lactoseFree: "no",
        glutenFree: "unknown",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "yes",
        NUT: "no",
      },
    },
    {
      fidId: "14A64E9",
      names: {
        en: ["egg"],
        de: ["Ei", "Hühnerei", "Hühnervollei", "Vollei"],
        hu: ["tojás"],
      },
      dietary: {
        vegan: "no",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "yes",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "588D661",
      names: {
        en: ["dry yeast"],
        de: ["Trockenhefe"],
        hu: ["száraz élesztő"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "unknown",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "569480A",
      names: {
        en: ["vanilla sugar"],
        de: ["Vanillezucker"],
        hu: ["vaníliás cukor"],
      },
      dietary: {
        vegan: "unknown",
        vegetarian: "unknown",
        lactoseFree: "unknown",
        glutenFree: "unknown",
      },
      allergens: {
        CCG: "unknown",
        EGG: "unknown",
        PEN: "unknown",
        MIL: "unknown",
        NUT: "unknown",
      },
    },
    {
      fidId: "5CDA2A6",
      names: {
        en: ["cocoa powder"],
        de: ["Kakaopulver"],
        hu: ["kakaó por"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "185FB6F",
      names: {
        en: ["honey"],
        de: ["Honig"],
        hu: ["méz"],
      },
      dietary: {
        vegan: "no",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "unknown",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "22F4A0C",
      names: {
        en: ["almond"],
        de: ["Mandel"],
        hu: ["mandula"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "yes",
      },
    },
    {
      fidId: "007BBC5",
      names: {
        en: ["salt"],
        de: [
          "feines Salz",
          "grobes Salz",
          "Pfannensalz",
          "Salinensalz",
          "Salz",
          "Siedesalz",
          "Speisesalz",
        ],
        hu: ["só"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
    {
      fidId: "4B24CC7",
      names: {
        en: ["dark chocolate"],
        de: ["Dunkle Schokolade", "Kuvertüre dunkel", "Zartbitter-Schokolade"],
        hu: ["étcsokoládé"],
      },
      dietary: {
        vegan: "unknown",
        vegetarian: "unknown",
        lactoseFree: "unknown",
        glutenFree: "unknown",
      },
      allergens: {
        CCG: "unknown",
        EGG: "unknown",
        PEN: "unknown",
        MIL: "unknown",
        NUT: "unknown",
      },
    },
    {
      fidId: "06CB219",
      names: {
        en: ["milk"],
        de: ["Milch"],
        hu: ["tej"],
      },
      dietary: {
        vegan: "no",
        vegetarian: "yes",
        lactoseFree: "no",
        glutenFree: "yes",
      },
      allergens: {
        CCG: "no",
        EGG: "no",
        PEN: "no",
        MIL: "yes",
        NUT: "no",
      },
    },
    {
      fidId: "6B83483",
      names: {
        en: ["rolled oat"],
        de: ["Haferflocken"],
        hu: ["zabpehely"],
      },
      dietary: {
        vegan: "yes",
        vegetarian: "yes",
        lactoseFree: "yes",
        glutenFree: "no",
      },
      allergens: {
        CCG: "yes",
        EGG: "no",
        PEN: "no",
        MIL: "no",
        NUT: "no",
      },
    },
  ],
  allergens: [
    {
      id: 1,
      code: "CCG",
      names: {
        en: "Cereals containing gluten",
        de: "Glutenhaltiges Getreide",
        hu: "Glutént tartalmazó gabonafélék",
        lt: "Glitimo turintys javai",
        pl: "Zboża zawierające gluten",
        uk: "Злаки, що містять глютен",
      },
    },
    {
      id: 13,
      code: "MIL",
      names: {
        en: "Milk",
        de: "Milch",
        hu: "Tej",
        lt: "Pienas",
        pl: "Mleko",
        uk: "Молоко",
      },
    },
    {
      id: 14,
      code: "NUT",
      names: {
        en: "Nuts",
        de: "Schalenfrüchte",
        hu: "Diófélék",
        lt: "Riešutai",
        pl: "Orzechy",
        uk: "Горіхи",
      },
    },
    {
      id: 11,
      code: "PEN",
      names: {
        en: "Peanuts",
        de: "Erdnüsse",
        hu: "Földimogyoró",
        lt: "Žemės riešutai",
        pl: "Orzeszki ziemne",
        uk: "Арахіс",
      },
    },
    {
      id: 9,
      code: "EGG",
      names: {
        en: "Eggs",
        de: "Eier",
        hu: "Tojás",
        lt: "Kiaušiniai",
        pl: "Jaja",
        uk: "Яйця",
      },
    },
  ],
} satisfies FidSnapshot;
