/**
 * fid-snapshot — the FID reference data first run needs offline (001 FR-014–FR-017, the
 * coordinator's Q3 ruling): the 13 staples and the allergen vocabulary the dietary mapping uses,
 * named in every UI locale FID carries. Read through the contract-typed client, never hand-typed.
 *
 * Run ONLY against a LOCAL api checked out at contract/SOURCE's commit and seeded with
 * `fid:import` — never production. `--api-commit` must equal that commit.
 *
 * Usage: NUTRIMERO_API_URL=http://localhost:4198 NUTRIMERO_API_TOKEN=… \
 *        node scripts/fid-snapshot.mts --api-commit <40-hex>
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createApiClient } from "../packages/core/src/api/client.ts";
import { MAPPED_ALLERGEN_CODES } from "../packages/features/diet-profile/src/mapping.ts";
import { STAPLE_FID_IDS } from "../packages/features/diet-profile/src/staples.ts";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(ROOT, "packages/features/diet-profile/src/fid-snapshot.generated.ts");

/** UI locale → the FID language whose names it shows (FID has no Belarusian yet). */
const FID_LANGUAGE: Record<string, string | null> = {
  en: "en-US",
  de: "de-DE",
  hu: "hu-HU",
  lt: "lt-LT",
  be: null,
  pl: "pl-PL",
  uk: "uk-UA",
};

function arg(name: string): string {
  const at = process.argv.indexOf(name);
  const value = at >= 0 ? process.argv[at + 1] : undefined;
  if (!value) throw new Error(`missing ${name}`);
  return value;
}

const apiCommit = arg("--api-commit");
const contractSource = readFileSync(path.join(ROOT, "contract/SOURCE"), "utf8").trim();
if (!/^[0-9a-f]{40}$/.test(apiCommit) || !contractSource.includes(apiCommit)) {
  throw new Error(`--api-commit must be the 40-hex commit in contract/SOURCE (${contractSource})`);
}
const baseUrl = process.env.NUTRIMERO_API_URL ?? "";
const token = process.env.NUTRIMERO_API_TOKEN ?? "";
if (!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/.test(baseUrl)) {
  throw new Error(
    "NUTRIMERO_API_URL must be a LOCAL api (http://localhost:PORT) — never production",
  );
}
const client = createApiClient(baseUrl);
const headers = { Authorization: `Bearer ${token}` };

const languages = await client.GET("/api/v1/fid/languages", {
  params: { query: { limit: 100 } },
  headers,
});
const languageId = new Map((languages.data?.items ?? []).map((l) => [l.locale, l.id]));

const staples = [];
for (const fidId of STAPLE_FID_IDS) {
  const { data } = await client.GET("/api/v1/fid/ingredients/{fidId}", {
    params: { path: { fidId } },
    headers,
  });
  if (!data) throw new Error(`staple ${fidId} does not resolve`);
  // Every name per language, in the api's order: the contract names no primary/display name.
  const names: Record<string, string[]> = {};
  for (const [ui, fid] of Object.entries(FID_LANGUAGE)) {
    const id = fid === null ? undefined : languageId.get(fid);
    const all = data.names.filter((n) => n.languageId === id).map((n) => n.name);
    if (all.length > 0) names[ui] = all;
  }
  const allergens = Object.fromEntries(
    data.allergens
      .filter((a) => MAPPED_ALLERGEN_CODES.includes(a.code))
      .map((a) => [a.code, a.state]),
  );
  staples.push({ fidId, names, dietary: data.dietary, allergens });
}

const vocabulary = new Map<string, { id: number; code: string; names: Record<string, string> }>();
for (const [ui, fid] of Object.entries(FID_LANGUAGE)) {
  if (fid === null) continue;
  const { data } = await client.GET("/api/v1/fid/allergens", {
    params: { query: { limit: 100, language: fid } },
    headers,
  });
  for (const a of data?.items ?? []) {
    if (!MAPPED_ALLERGEN_CODES.includes(a.code)) continue;
    const entry = vocabulary.get(a.code) ?? { id: a.id, code: a.code, names: {} };
    if (a.name) entry.names[ui] = a.name;
    vocabulary.set(a.code, entry);
  }
}

const snapshot = {
  apiCommit,
  contractSource,
  staples,
  allergens: MAPPED_ALLERGEN_CODES.map(
    (code) => vocabulary.get(code) ?? { id: -1, code, names: {} },
  ),
};

writeFileSync(
  OUTPUT,
  `// GENERATED by scripts/fid-snapshot.mts — DO NOT EDIT. A hand edit is a suppression-class
// violation (Constitution XII); regenerate from a LOCAL api instead.
// Taken ${new Date().toISOString().slice(0, 10)} from a LOCAL nutrimero-api at ${apiCommit} (contract/SOURCE),
// seeded with fid:import — NOT from api main, which has moved on (#80–#82: the declaration
// reference, refuse-on-gap issuing, the peanut/sulphite allergen guard); none of it changes these
// FID reads. Never taken from production.
import type { FidSnapshot } from "./fid-snapshot-types";

export const FID_SNAPSHOT = ${JSON.stringify(snapshot, null, 2)} satisfies FidSnapshot;
`,
);
// The repository's formatter is the last step of generation, so the committed file is exactly
// this script's output and the quality gate needs no exclusion for it.
execFileSync("pnpm", ["exec", "biome", "format", "--write", OUTPUT], {
  cwd: ROOT,
  stdio: "ignore",
});
console.log(
  `✓ ${path.relative(ROOT, OUTPUT)}: ${staples.length} staples, ${snapshot.allergens.length} allergens`,
);
